### ISSUE TITLE
Enabling BLE

### ISSUE THREAD

**Issue by trash-anger** [joeycastillo/Sensor-Watch#20]
Hi Joey,

Do you think there space for tiny ble antena and ship ?

**Comment by joeycastillo** [comment]
I have my doubts, if I'm being perfectly honest. The only space available for something like this would be on a small sensor board connected over the 9-pin connector, and there's just not a lot of room in there. Additionally, the power budget for this device has a hard ceiling at 100 milliampere hours due to the size and shape of the coin cell involved. To keep the thing as small as it is, and to make it work for as long as we want it to, my sense is that BLE is going to be out of scope.

Having said that, far be it from me to say what is and isn't possible. The sensor board spec is open, and [others have suggested chips that may make this possible](https://github.com/joeycastillo/Sensor-Watch/issues/11). It's not something I personally foresee putting on the roadmap (which is why I'm closing the issue), but if the someone wants to try making a tiny BLE add-on board for the watch, I'd be thrilled to see what they can do.
